<a href="https://colab.research.google.com/github/kevengoncalves-git/tecnicas_adversarias/blob/Edu/Inserir_N_gramas_de_Shap_em_EXE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#shap

In [1]:
!pip install Shap

Requirement already satisfied: Shap in /usr/local/lib/python3.11/dist-packages (0.48.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from Shap) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from Shap) (1.15.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from Shap) (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from Shap) (2.2.2)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.11/dist-packages (from Shap) (4.67.1)
Requirement already satisfied: packaging>20.9 in /usr/local/lib/python3.11/dist-packages (from Shap) (24.2)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.11/dist-packages (from Shap) (0.0.8)
Requirement already satisfied: numba>=0.54 in /usr/local/lib/python3.11/dist-packages (from Shap) (0.60.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.11/dist-packages (from Shap) (3.1.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/dist-packages (from Shap) (4.14.1)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba>=0.54->Shap) (0.43.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->Shap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->Shap) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->Shap) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->Shap) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->Shap) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->Shap) (1.17.0)

##Bibliotecas Importadas

In [2]:
import pandas as pd
import shap
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier, ExtraTreesClassifier
from sklearn.ensemble import VotingClassifier

In [3]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, precision_score, recall_score, f1_score
from sklearn.utils import shuffle
import matplotlib.pyplot as plt

##Importar DataSet

In [4]:
df_test = pd.read_csv('/content/df_test_4gram.csv').drop('Unnamed: 0', axis=1)
df_train = pd.read_csv('/content/df_train_processado_4gram.csv').drop('Unnamed: 0', axis=1)

##Criação do Soft Volting

In [5]:
#melhores resultados 4gramas
lr_clf = LogisticRegression(C=0.1, max_iter=150, solver='liblinear')
ext_clf = ExtraTreesClassifier(criterion='entropy', max_depth=6, n_estimators=250)
ad_clf = AdaBoostClassifier(learning_rate=0.1, n_estimators=300)

sf_clf = VotingClassifier(
    estimators=[('lr', lr_clf), ('ext', ext_clf), ('ad', ad_clf)],
    voting='soft')

In [6]:
modelo = sf_clf

## SHAP

In [7]:
df_test = shuffle(df_test)
df_test

,ID,Filename,RG,Family,this program cannot run,program cannot run dos,cannot run dos mode,idata idata idata idata,run dos mode text,kernel32 dll kernel32 dll,...,chttp www microsoft com,ehttp www microsoft com,com pkiops crl crl0a,pkiops crl crl0a ehttp,crl crl0a ehttp www,com pkiops certs crt0,crl0a ehttp www microsoft,tsh tsh tsh tsh,std allocator std std.1,svwh svwh svwh svwh
101,10101,KompoZerPortable_0.8_Beta_3_English.paf.exe,0,0,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
431,10298,8fb307c24f655cc773d692f1354c4c6e265e5e275f6637...,1,32,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
161,10028,176476f9d924d83343a51a90ade097d12b7594dc5dbca1...,1,39,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
99,10099,Notepad2-modPortable_4.2.25.998_English.paf.exe,0,0,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
467,10334,c0514cd580275b54f5b1d69086c9f415e7afb805479bfe...,1,31,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,10156,b5daf399518d76b8e7ca86ada767d9e90fd0ae6efbe5ac...,1,33,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
513,10380,623b69c1fd45686af03cd87f77d6e3e17b263e1cf70a25...,1,38,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
376,10243,1f102cc8bb6a14cc2bd9b9311acb66ed5a6035e8510ea3...,1,26,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
468,10335,2ee6dfbfb2afd7442c9f2212eb142876698851c3ffb552...,1,31,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
60,10060,WinDock_Setup_1_2_1.exe,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
df_train.iloc[:2,:]

,ID,Filename,RG,Family,this program cannot run,program cannot run dos,cannot run dos mode,idata idata idata idata,run dos mode text,kernel32 dll kernel32 dll,...,chttp www microsoft com,ehttp www microsoft com,com pkiops crl crl0a,pkiops crl crl0a ehttp,crl crl0a ehttp www,com pkiops certs crt0,crl0a ehttp www microsoft,tsh tsh tsh tsh,std allocator std std.1,svwh svwh svwh svwh
0,10000,2XClient_12.0_build_2193.paf.exe,0,0,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,10001,7-ZipPortable_21.07.paf.exe,0,0,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
X, y = df_train.drop(["RG", "Filename", "Family", "ID"], axis=1), df_train['RG']

In [16]:
X_test, y_test = df_test.iloc[:10,:].drop(["RG", "Filename", "Family", "ID"], axis=1), df_test.iloc[:10,:]['RG']

In [17]:
y_test.value_counts()

RG
1    7
0    3
Name: count, dtype: int64

In [14]:
modelo.fit(X,y)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(C=0.1, max_iter=150,
                                                 solver='liblinear')),
                             ('ext',
                              ExtraTreesClassifier(criterion='entropy',
                                                   max_depth=6,
                                                   n_estimators=250)),
                             ('ad',
                              AdaBoostClassifier(learning_rate=0.1,
                                                 n_estimators=300))],
                 voting='soft')

In [18]:
res = modelo.predict(X_test)
print('Acc: ',accuracy_score(y_test,res)*100)
print('Prec: ',precision_score(y_test,res)*100)
print('Rec: ',recall_score(y_test,res)*100)
print('F1: ',f1_score(y_test,res)*100)

Acc:  100.0
Prec:  100.0
Rec:  100.0
F1:  100.0

In [19]:
def comparar_arrays(array1, array2):
  """
  Compara dois arrays de tamanhos iguais e retorna um array booleano com True
  onde os valores comparados são iguais e False onde são diferentes.

  Args:
    array1: O primeiro array.
    array2: O segundo array.

  Returns:
    Um array booleano do mesmo tamanho, indicando as posições com valores iguais (True) e diferentes (False).
  """
  if len(array1) != len(array2):
    raise ValueError("Os arrays devem ter o mesmo tamanho.")

  resultado = []
  for i in range(len(array1)):
    resultado.append(bool(array1[i] != array2[i]))

  return resultado

In [20]:
misclassified = comparar_arrays(modelo.predict(X_test), y_test.values)
print(misclassified)

[False, False, False, False, False, False, False, False, False, False]

In [21]:
explainer = shap.Explainer(modelo.predict_proba, X)
shap_values = explainer(X_test, max_evals=4000) # Número ainda não decidido # maior que 3285

PermutationExplainer explainer: 11it [22:50, 137.01s/it]

Salvar shap e combinar

In [24]:
# prompt: salvar shap_values = explainer(X_test, max_evals=4000)

# The shap values were already calculated in the preceding code.
# This response will save the shap_values to a file.

import pickle

# Save the shap_values
with open('shap_values.pkl', 'wb') as f:
    pickle.dump(shap_values, f)

print("shap_values saved to shap_values.pkl")

shap_values saved to shap_values.pkl

In [25]:
# prompt: importar shap_values.pkl

# The shap values were saved in the preceding code.
# This response will load the shap_values from a file.

# Load the shap_values
with open('shap_values.pkl', 'rb') as f:
    loaded_shap_values = pickle.load(f)

print("shap_values loaded from shap_values.pkl")
# You can now use loaded_shap_values for further analysis or plotting.
# For example, you can print the type of the loaded object
print(type(loaded_shap_values))

shap_values loaded from shap_values.pkl
<class 'shap._explanation.Explanation'>

In [26]:
loaded_shap_values

.values =
array([[[-1.89504336e-04,  1.89504336e-04],
        [-1.91131292e-04,  1.91131292e-04],
        [-7.94239576e-05,  7.94239576e-05],
        ...,
        [ 0.00000000e+00,  0.00000000e+00],
        [ 3.20820678e-06, -3.20820678e-06],
        [-1.94922040e-08,  1.94922040e-08]],

       [[-1.31799748e-04,  1.31799748e-04],
        [-1.37173904e-04,  1.37173904e-04],
        [-8.00415207e-05,  8.00415207e-05],
        ...,
        [ 0.00000000e+00,  0.00000000e+00],
        [ 1.84176770e-05, -1.84176770e-05],
        [-1.31594902e-05,  1.31594902e-05]],

       [[-2.23622364e-05,  2.23622364e-05],
        [-3.88032559e-05,  3.88032559e-05],
        [-3.32103225e-05,  3.32103225e-05],
        ...,
        [ 0.00000000e+00,  0.00000000e+00],
        [ 6.33916171e-06, -6.33916171e-06],
        [-1.36075507e-05,  1.36075507e-05]],

       ...,

       [[-1.85809301e-05,  1.85809301e-05],
        [-1.60447955e-05,  1.60447955e-05],
        [-3.46283116e-05,  3.46283116e-05],
        ...,
        [ 0.00000000e+00,  0.00000000e+00],
        [ 7.02893180e-06, -7.02893180e-06],
        [-1.27133281e-05,  1.27133281e-05]],

       [[ 4.46765752e-03, -4.46765752e-03],
        [ 3.87517165e-03, -3.87517165e-03],
        [ 4.01018687e-03, -4.01018687e-03],
        ...,
        [ 0.00000000e+00,  0.00000000e+00],
        [ 6.66016713e-06, -6.66016713e-06],
        [-3.05590234e-07,  3.05590234e-07]],

       [[-4.05432434e-05,  4.05432434e-05],
        [-2.51910879e-05,  2.51910879e-05],
        [-4.37122331e-05,  4.37122331e-05],
        ...,
        [ 0.00000000e+00,  0.00000000e+00],
        [ 1.70525054e-05, -1.70525054e-05],
        [-1.35517624e-05,  1.35517624e-05]]])

.base_values =
array([[0.57081715, 0.42918285],
       [0.57081715, 0.42918285],
       [0.57081715, 0.42918285],
       [0.57081715, 0.42918285],
       [0.57081715, 0.42918285],
       [0.57081715, 0.42918285],
       [0.57081715, 0.42918285],
       [0.57081715, 0.42918285],
       [0.57081715, 0.42918285],
       [0.57081715, 0.42918285]])

.data =
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])

In [23]:
shap_values

array([[[-1.89504336e-04,  1.89504336e-04],
        [-1.91131292e-04,  1.91131292e-04],
        [-7.94239576e-05,  7.94239576e-05],
        ...,
        [ 0.00000000e+00,  0.00000000e+00],
        [ 3.20820678e-06, -3.20820678e-06],
        [-1.94922040e-08,  1.94922040e-08]],

       [[-1.31799748e-04,  1.31799748e-04],
        [-1.37173904e-04,  1.37173904e-04],
        [-8.00415207e-05,  8.00415207e-05],
        ...,
        [ 0.00000000e+00,  0.00000000e+00],
        [ 1.84176770e-05, -1.84176770e-05],
        [-1.31594902e-05,  1.31594902e-05]],

       [[-2.23622364e-05,  2.23622364e-05],
        [-3.88032559e-05,  3.88032559e-05],
        [-3.32103225e-05,  3.32103225e-05],
        ...,
        [ 0.00000000e+00,  0.00000000e+00],
        [ 6.33916171e-06, -6.33916171e-06],
        [-1.36075507e-05,  1.36075507e-05]],

       ...,

       [[-1.85809301e-05,  1.85809301e-05],
        [-1.60447955e-05,  1.60447955e-05],
        [-3.46283116e-05,  3.46283116e-05],
        ...,
        [ 0.00000000e+00,  0.00000000e+00],
        [ 7.02893180e-06, -7.02893180e-06],
        [-1.27133281e-05,  1.27133281e-05]],

       [[ 4.46765752e-03, -4.46765752e-03],
        [ 3.87517165e-03, -3.87517165e-03],
        [ 4.01018687e-03, -4.01018687e-03],
        ...,
        [ 0.00000000e+00,  0.00000000e+00],
        [ 6.66016713e-06, -6.66016713e-06],
        [-3.05590234e-07,  3.05590234e-07]],

       [[-4.05432434e-05,  4.05432434e-05],
        [-2.51910879e-05,  2.51910879e-05],
        [-4.37122331e-05,  4.37122331e-05],
        ...,
        [ 0.00000000e+00,  0.00000000e+00],
        [ 1.70525054e-05, -1.70525054e-05],
        [-1.35517624e-05,  1.35517624e-05]]])

In [ ]:
# prompt: juntar 2 shaps_values

# Assuming `shap_values` and `loaded_shap_values` are SHAP Explainer objects with a `.values` attribute
# that contains the SHAP values as a NumPy array.
# Check if the loaded SHAP values have the same shape as the original ones before concatenating.
if loaded_shap_values.values.shape[1] == shap_values.values.shape[1]:
  # Concatenate the SHAP values along the first axis (rows)
  combined_shap_values_values = np.concatenate((shap_values.values, loaded_shap_values.values), axis=0)

  # Create a new SHAP Explainer object with the combined values
  # You might need to adjust this based on the structure of your SHAP Explainer object
  # This is a simplified example assuming the .values attribute is sufficient
  combined_shap_values = shap.Explanation(
      combined_shap_values_values,
      base_values=np.concatenate((shap_values.base_values, loaded_shap_values.base_values), axis=0) if hasattr(shap_values, 'base_values') and hasattr(loaded_shap_values, 'base_values') else None,
      data=np.concatenate((shap_values.data, loaded_shap_values.data), axis=0) if hasattr(shap_values, 'data') and hasattr(loaded_shap_values, 'data') else None,
      feature_names=shap_values.feature_names # Assuming feature names are the same
  )

  print("SHAP values combined successfully.")
  print("Shape of combined SHAP values:", combined_shap_values.values.shape)
else:
  print("SHAP value shapes do not match. Cannot combine.")
  print("Shape of original shap_values:", shap_values.values.shape)
  print("Shape of loaded_shap_values:", loaded_shap_values.values.shape)

In [ ]:
shap_values.base_values[1][1]

In [ ]:
# com predict_proba
shap.plots.decision(shap_values.base_values[1][1],shap_values[...,1].values,
                   highlight=misclassified,
                   features=X_test,
                   feature_display_range=slice(-1, -101, -1),
                    new_base_value=0.5,
                    # xlim=(-0.05,1.05),
                    auto_size_plot = False,
                    title="Valor de saída do modelo",
                    show=False,
                    ignore_warnings=True # Add this argument
                   )
plt.gcf().set_size_inches(6,25)
plt.savefig(f'decision_proba_{modelo.__class__.__name__}_allfamily.pdf', format='pdf', dpi=600, bbox_inches='tight')
plt.show()

In [ ]:
fig = plt.figure()
shap.plots.beeswarm(shap_values[...,1], max_display=101,show = False)
plt.gcf().set_size_inches(6,25)
plt.savefig(f'beeswarm_{modelo.__class__.__name__}_allfamily.pdf', format='pdf', dpi=600, bbox_inches='tight')
plt.show()

#teste unitaio

In [ ]:
import re
import pandas as pd

In [ ]:
def extrair_strings (caminho_arquivo):
  strings_extraidas = []
  with open(caminho_arquivo, 'rb') as f:
     conteudo = f.read()
     strings_encontradas = re.findall(r'\b(?=[a-zA-Z]{4,})(?:[a-zA-Z0-9])+\b', conteudo.decode('latin-1', errors='ignore'))
     string_unica = ' '.join(strings_encontradas).lower()
     strings_extraidas.append(string_unica)
  return strings_extraidas

In [ ]:
def criar_data (strings_extraidas, colunas, rg):
        # Preenche as colunas de ngrams
        # Add 'RG' to the list of columns when creating the DataFrame
        dataframe = pd.DataFrame(columns=['RG'] + colunas)
        linha = [0] * (len(colunas)+1)
        linha[0] = rg
        for j, coluna in enumerate(colunas):
            if coluna in strings_extraidas:
                linha[j+1] = 1  # Adiciona 1 na posição correta da coluna de ngram

        dataframe.loc[len(dataframe)] = linha  # Adiciona a linha ao DataFrame
        return dataframe

In [ ]:
colunas = df_test.columns.to_list()[4:]

In [ ]:
string1 = extrai_strings("/content/desktopcal-setup-v2.exe")

In [ ]:
df_unico = criar_data(string1, colunas, 0)
df_unico

,RG,this program cannot run,program cannot run dos,cannot run dos mode,idata idata idata idata,run dos mode text,kernel32 dll kernel32 dll,lhx zjz knv owg,text rdata data reloc,svw svw svw svw,...,chttp www microsoft com,ehttp www microsoft com,com pkiops crl crl0a,pkiops crl crl0a ehttp,crl crl0a ehttp www,com pkiops certs crt0,crl0a ehttp www microsoft,tsh tsh tsh tsh,std allocator std std.1,svwh svwh svwh svwh
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0